# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.8   #base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "install docker client"
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli
      - run:
          name: "Say hello all"
          command: "echo Hello, World!"
      - run:
          name: Install Pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
      - run:
          name: Install Dependencies
          command: |
            pip install pytest

# Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/tdd:${CIRCLE_SHA1} -f .circleci/Dockerfile .
      - run:
          name: Docker Hub Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin

     
      # Push Docker image to Docker Hub
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/tdd:${CIRCLE_SHA1}
      - run:
          name: "Say bye"
          command: "echo bye guys see you ,astlavista"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-pushworkflow:
    jobs:
      - build-and-push
